# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuil', models.CharField(db_index=True, max_length=11, unique=True)),
                ('razon_social', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('mail', models.EmailField(max_length=254)),
                ('alta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
