# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 04:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaFactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_prod', models.IntegerField()),
                ('detalle', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unit', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ('nombre',)},
        ),
        migrations.AlterModelOptions(
            name='factura',
            options={'ordering': ('f_vencimiento',)},
        ),
        migrations.AddField(
            model_name='lineafactura',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_x_linea', to='clientes.Factura'),
        ),
    ]
